{% set name = "pineappl" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NNPDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: a3ffda93de167028e6f7c5e27923d456c176c95159a9245374008c5167e8b7e5

build:
  number: 0
  skip: true  # [win]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - maturin
    - {{ compiler('rust') }} >=1.70
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - pkg-config
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/NNPDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
    - cschwan
