{% set name = "pineappl" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: e4832ddbed4b6dba1df8d35c66af085afa7b21ae1c3b7411eaaa747baf614abc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }} >=1.45
  host:
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/N3PDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarrazza
    - cschwan
