{% set name = "pineappl" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: 21283bc3b8ba21b1e864ff3f85e71acda3bceea1d2321bf719965139a7a61d8d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }} >=1.45
  host:
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/N3PDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarrazza
    - cschwan
