{% set name = "pineappl" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NNPDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: 0785eb002fea460295f6348bcbcebacc5ee72d4280a8caee1c7a47ce45661e3a

build:
  number: 0
  skip: true  # [win]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - maturin
    - {{ compiler('rust') }} >=1.70
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - pkg-config
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/NNPDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - Radonirinaunimi
    - scarlehoff
    - scarrazza
    - cschwan
