{% set name = "pineappl" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: d18fae34c29543fb20855c3b54cea624db48002e4fd61aefc7d8c66670fc09d3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }} >=1.45
  host:
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/N3PDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarrazza
    - cschwan
