{% set name = "pineappl" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: 5d391357f0c4af7b351e47b3cc9c6e418c8a91a5fa9933b77e1133effb58b65a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }} >=1.45
  host:
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/N3PDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarrazza
    - cschwan
