{% set name = "pineappl" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NNPDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: 6534855a76d6d91b734218e66b6d1f2e558cf25865498b03172a713d173e90e7

build:
  number: 2
  skip: true  # [win]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - maturin
    - {{ compiler('rust') }} >=1.70
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - {{ compiler('c') }}
    - pkg-config
    - python
    - pip
    - maturin
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
    - python
    - numpy

test:
  imports:
    - pineappl

about:
  home: https://github.com/NNPDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
    - cschwan
