{% set name = "pineappl" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pineappl-{{ version }}.tar.gz
  sha256: 0f682ce32228b4d63089b45ff667efb0322e927c0522db5a83408d468b185973

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - maturin >=0.13.4
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.0,<2.0.0

test:
  imports:
    - pineappl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NNPDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python bindings to PineAPPL

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
    - cschwan
