schema_version: 1

context:
  name: pineappl
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NNPDF/pineappl/archive/v${{ version }}.tar.gz
  sha256: d26d322fedbc93fa04d3f162ad2367f47c70dec6409f1860159c73dc00ce1648

build:
  number: 0
  skip:
    - pypy
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - maturin
    - ${{ compiler('rust') }} >=1.70
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - ${{ compiler('c') }}
    - pkg-config
    - lhapdf
    - python
    - pip
    - maturin
  run:
    - pkg-config
    - lhapdf
    - python
    - numpy

tests:
  - python:
      imports:
        - pineappl

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.
  homepage: https://github.com/NNPDF/pineappl

extra:
  recipe-maintainers:
    - Radonirinaunimi
    - scarlehoff
    - scarrazza
    - cschwan
